name: memento_mori_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0 # –ü–æ–Ω–∏–∑–∏–ª —Ç—Ä–µ–±–æ–≤–∞–Ω–∏–µ, —á—Ç–æ–±—ã –ø–∞–∫–µ—Ç—ã —Ç–æ—á–Ω–æ –ø–æ–¥–æ—à–ª–∏ (3.9.2 –ø–æ–∫–∞ –Ω–µ —Å—É—â–µ—Å—Ç–≤—É–µ—Ç –≤ —Å—Ç–∞–±–∏–ª—å–Ω–æ–π –≤–µ—Ç–∫–µ)

dependencies:
  flutter:
    sdk: flutter

  # --- UI & –õ–æ–∫–∞–ª–∏–∑–∞—Ü–∏—è ---
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  animate_do: ^4.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  app_settings: ^6.1.1
  math_expressions: ^2.4.0
  # --- –ê—É–¥–∏–æ (—Ç—ã –¥–æ–±–∞–≤–∏–ª, –ø—É—Å—Ç—å –±—É–¥–µ—Ç –¥–ª—è –∑–≤—É–∫–æ–≤ —Ç–∞–π–º–µ—Ä–∞/—á–∞—Ç–∞) ---
  audioplayers: ^6.5.1

  # --- –°–µ—Ç—å –∏ –î–∞–Ω–Ω—ã–µ (–ë—ç–∫–µ–Ω–¥) ---
  http: ^1.5.0
  web_socket_channel: ^3.0.3
  flutter_secure_storage: ^9.2.4
  geolocator: ^13.0.1
  device_info_plus: ^10.1.0
  flutter_ble_peripheral: ^2.0.1
  get_it: ^7.7.0
  provider: ^6.1.1
  flutter_foreground_task: ^6.1.1
  sensors_plus: ^6.1.1
  shared_preferences: ^2.2.2
  local_auth: ^2.1.6
  sqflite: ^2.3.0
  path: ^1.8.3
  wakelock_plus: ^1.2.8
  just_audio: ^0.9.36
  # –î–ª—è –ø–æ–ª–Ω–æ—Ü–µ–Ω–Ω–æ–≥–æ –¥–µ–∫–æ–¥–∏—Ä–æ–≤–∞–Ω–∏—è (FFT) –ø–æ–∑–∂–µ –ø–æ–Ω–∞–¥–æ–±–∏—Ç—Å—è:
  # fftea: ^1.1.0
  flutter_local_notifications: ^17.1.2

  cryptography: ^2.5.0

  # --- üî• –ù–û–í–´–ï –ó–ê–í–ò–°–ò–ú–û–°–¢–ò (–û–§–§–õ–ê–ô–ù/MESH) ---
  nearby_connections: ^4.0.0
    # 2. Universal P2P (–¥–ª—è Huawei –∏ –æ—Å—Ç–∞–ª—å–Ω—ã—Ö)

  flutter_blue_plus: ^1.34.5
  sound_generator: ^0.0.14
  fftea: ^1.1.2



  # 3. –ü—Ä–æ–≤–µ—Ä–∫–∞ –Ω–∞–ª–∏—á–∏—è Google Services

  permission_handler: ^11.3.1 # –ó–∞–ø—Ä–æ—Å —Ä–∞–∑—Ä–µ—à–µ–Ω–∏–π Android
  uuid: ^4.4.0                # –ì–µ–Ω–µ—Ä–∞—Ü–∏—è —É–Ω–∏–∫–∞–ª—å–Ω—ã—Ö ID –¥–ª—è Mesh-–∑–∞–ø—Ä–æ—Å–æ–≤

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # --- –î–ª—è —Å–º–µ–Ω—ã –∏–∫–æ–Ω–∫–∏ –Ω–∞ –ö–∞–ª—å–∫—É–ª—è—Ç–æ—Ä ---
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  generate: true
  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron Bold.ttf
  # –ê—Å—Å–µ—Ç—ã
  assets:
    - assets/audio/
    # –ù–µ –∑–∞–±—É–¥—å —Å–æ–∑–¥–∞—Ç—å —ç—Ç—É –ø–∞–ø–∫—É, –µ—Å–ª–∏ —Ö–æ—á–µ—à—å –º–µ–Ω—è—Ç—å –∏–∫–æ–Ω–∫—É —á–µ—Ä–µ–∑ –∫–æ–Ω—Ñ–∏–≥:
    # - assets/icon/

# –ù–∞—Å—Ç—Ä–æ–π–∫–∞ –∏–∫–æ–Ω–∫–∏ (—Ä–∞—Å–∫–æ–º–º–µ–Ω—Ç–∏—Ä—É–π –∏ –ø–æ–ª–æ–∂–∏ –∫–∞—Ä—Ç–∏–Ω–∫—É, –∫–æ–≥–¥–∞ –±—É–¥–µ—à—å –≥–æ—Ç–æ–≤)
# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icon/calculator.png"
#   min_sdk_android: 21